# -*- coding: utf-8 -*-
"""Monta_Árvore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUkopAUpbSIWgzO9FlSc1F5OAFIBrrPo
"""

'''
2) Elabore um algoritmo onde o usuário fornecerá a altura da árvore e o 
caractere para a sua construção, sabendo-se que: a altura mínima da árvore é de 
6 linhas e a altura máxima da árvore será 24 linhas, incluindo uma linha para a 
base e duas linhas para o tronco.  Em geral o terminal texto tem as seguintes 
medidas: 80x25 colunasxlinhas.
Exemplo de uma árvore de altura 6, utilizando o caractere <*>:
 
                                       *
                                      ***
                                     *****
                                       *
                                       *
                                     *****
1 DECLARAR VARIÁVEIS
1.2 altura, caracter, folha, cespaco, ccaracter, contador
2 SOLICITAR A ALTURA (altura)
3 SOLICITAR O CARACTER (carcter)
6 SE altura <= 6 ENTÃO
  6.1 altura <- 6
7 FIM SE
8 SE altura >= 24
  8.1 altura <- 24  
9 FIM SE
10 folha <- 1   # quandidade de asteristicos a serem desenhados
11 FAÇA contador <- 1 ATÉ  altura - 3
  # ESCREVE O NUMERO DE ESPAÇOS - QUANTIDADE DE ROUND(FOLHAS/2)
  11.1 FAÇA cespaco <- 1 ATÉ 40 - contador
    11.1.1 MOSTRAR " "
  11.2 FIM FAÇA
  # ESCREVE OS CARACTETES QUE FORMARÃO AS FOLHAS (*)
  11.4 FAÇA ccaracter <- 1 ATÉ folha
    11.4.1 MOSTRAR caracter
  11.5 FIM FAÇA
  11.6 folha <- folha + 2
  # PULA LINHA
  11.7 MOSTRAR "\n"
12 FIM FAÇA
13 FAÇA contador <-1 ATÉ 2
  13.1 FAÇA cespaco <- 1 ATÉ 39
    13.1.1 MOSTRAR " "
  13.2 fim faça
  13.3 MOSTRAR caracter
  13.4 MOSTRAR "\n"
14 FIM FAÇA
15 FAÇA cespaco <- 1 ATÉ 37
  15.1 MOSTRAR " "
16 FIM FAÇA
17 FAÇA ccaracter <-1 ATÉ 5
  17.1 MOSTRAR caracter
18 FIM FAÇA
'''

def desenhacaracter(num, char=" "):
  while ( num ):
    print(char, end="")
    num = num -1

altura = int(input("Digite a altura: "))
caracter = input("Digite o caracter: ")
folhas = 1
contador = 1

if ( altura < 6 ):
  altura = 6
if ( altura > 24 ):
  altura = 24

while ( contador <= (altura - 3)):
  desenhacaracter(40 - contador)  # Espaço
  desenhacaracter(folhas, caracter)
  contador = contador + 1
  folhas = folhas + 2
  print(" ")

contador = 2
while ( contador ):
  desenhacaracter(39)
  desenhacaracter(1, caracter)
  print("")
  contador = contador - 1


desenhacaracter(37)
desenhacaracter(5, caracter)